services:
  #само приложение
  test:
    build: ./app
    container_name: test
    networks:
      - balance-net

  nginx1:
    image: nginx:alpine
    container_name: nginx1
    ports:
      - "8081:80"
    environment: #перменные для nginx.conf
      - UPSTREAM_1=nginx2
      - UPSTREAM_2=nginx3
      - UPSTREAM_APP=test
    volumes:
      - ./nginx.conf:/nginx.conf
    networks:
      - balance-net
    depends_on:
      - test
    command: /bin/sh -c "envsubst '$$UPSTREAM_1 $$UPSTREAM_2 $$UPSTREAM_APP' < /nginx.conf > /etc/nginx/nginx.conf && nginx" #подстановка переменных и запуск nginx

  nginx2:
    image: nginx:alpine
    container_name: nginx2
    ports:
      - "8082:80"
    environment:
      - UPSTREAM_1=nginx1
      - UPSTREAM_2=nginx3
      - UPSTREAM_APP=test
    volumes:
      - ./nginx.conf:/nginx.conf
    networks:
      - balance-net
    depends_on:
      - test
    command: /bin/sh -c "envsubst '$$UPSTREAM_1 $$UPSTREAM_2 $$UPSTREAM_APP' < /nginx.conf > /etc/nginx/nginx.conf && nginx"

  nginx3:
    image: nginx:alpine
    container_name: nginx3
    ports:
      - "8083:80"
    environment:
      - UPSTREAM_1=nginx1
      - UPSTREAM_2=nginx2
      - UPSTREAM_APP=test
    volumes:
      - ./nginx.conf:/nginx.conf
    networks:
      - balance-net
    depends_on:
      - test
    command: /bin/sh -c "envsubst '$$UPSTREAM_1 $$UPSTREAM_2 $$UPSTREAM_APP' < /nginx.conf > /etc/nginx/nginx.conf && nginx"

networks:
  balance-net:
    driver: bridge
