daemon off;
events {
    worker_connections 2000;
}
http {
    resolver 127.0.0.11 valid=10s; #DNS докера, иначе не найдет
    #проверка на первую обработку
    map $http_x_internal_net $checked {
        "1"     0;
        default 1;
    }
    map $checked $xff { 
        1       "$remote_addr, $server_addr";
        0       "$http_x_forwarded_for, $server_addr";
    }
    #апстримы подтянуться из docker-compose.yml
    upstream balance {
        server ${UPSTREAM_1}:80;
        server ${UPSTREAM_2}:80;
        server ${UPSTREAM_APP}:8080;
    }
    server {
        listen 80;
        location / {
            proxy_set_header X-Forwarded-For $xff;
            proxy_set_header X-Internal-Net "1"; #указатель что первую обработку запрос прошел
            proxy_pass http://balance;
        }
    }
}
